---
# Copyright (C) 2015 BROADSoftware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
#limitations under the License.
#

- name: Install shorewall package
  yum: pkg=shorewall state=present
  
- name: Create a folder to save original files
  file: path=/etc/shorewall/virgin state=directory owner=root group=root mode=0755

- name: Save original config files
  shell: mv /etc/shorewall/* /etc/shorewall/virgin/
  args:
    creates: /etc/shorewall/virgin/shorewall.conf
  failed_when: false

- name: Setup Shorewall config files
  template:
    src: "{{item}}.j2"
    dest: "/etc/shorewall/{{item}}"
    backup: yes
  with_items:
  - rules
  - zones
  - interfaces
  - masq
  - policy
  - shorewall.conf
  - stoppedrules
  notify: reload shorewall

#- meta: flush_handlers
    
- name: Enable shorewall
  service:
    name: shorewall
    enabled: yes
    state: started          

- name: reload shorewall in case of network restart 
  shell: shorewall restart
  when: (network_service_restart_notification1 is defined and network_service_restart_notification1.changed) or (network_service_restart_notification2 is defined and network_service_restart_notification2.changed)
    