---
# Copyright (C) 2015 BROADSoftware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
#limitations under the License.
#


- name: Create {{confluent_group}} group
  group:
    name: "{{confluent_group}}"
    system: true
    state: present

- name: Create {{schema_registry_user}} user
  user:
    name: "{{schema_registry_user}}"
    system: true
    createhome: no
    group: "{{confluent_group}}"
    shell: /sbin/nologin
    home: /tmp
    state: present


- name: Intall Schema registry package
  yum: pkg=confluent-schema-registry state=present

- name: Create log dir
  file: path={{confluent_log_dir}} owner=root group={{confluent_group}} mode=0775 state=directory
    
- name: Configure properties
  template: src=schema-registry.properties.j2 dest=/etc/schema-registry/schema-registry.properties owner=root group=root mode=0644 backup=yes
  notify:
  - restart schema-registry

- name: Configure log4j
  template: src=log4j.properties.j2 dest=/etc/schema-registry/log4j.properties owner=root group=root mode=0644 backup=yes
  notify:
  - restart schema-registry
  
- name: Create schema-registry service
  template:
    src: schema-registry.service.j2
    dest: /usr/lib/systemd/system/schema-registry.service
    owner: root
    group: root
    mode: 0644
    backup: no
  notify:
  - reload service file      
  - restart schema-registry
   
- meta: flush_handlers
   
- name: Ensure schema-registry service is enabled and started
  service:
    name: schema-registry
    enabled: yes
    state: started        
    
    
    
    
    
    
      