

# Using dnsmasq for DHCP requires that you use it for DNS. 
# So, to be more flexible, we will use isc dhcp, this letting DNS mgmt left to choice.



- name: Install packages
  yum: pkg=cobbler,cobbler-web,httpd,dhcp,yum-utils,pykickstart,xinetd   state=present
  
- name: Set config files
  template:
    src: "{{item}}.j2"
    dest: "/etc/cobbler/{{item}}"
    owner: root
    group: root
    mode: 0755
  with_items:
  - settings
  - modules.conf
  - tftpd.template
  notify:
  - Restart cobblerd
  - Cobbler sync
  - Restart xinetd
  
- name: Set snippet files in place
  template:
    src: "snippets/{{item}}.j2"
    dest: "/var/lib/cobbler/snippets/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - install_build_key_pub
  - install_host_key_pub
  - install_host_key_priv

- name: Create snippets paths
  file: path={{item}} owner=root group=root mode=0755 state=directory
  with_items:
  - /var/lib/cobbler/snippets/per_system/
  - /var/lib/cobbler/snippets/per_system/build_key_pub
  - /var/lib/cobbler/snippets/per_system/host_key_pub
  - /var/lib/cobbler/snippets/per_system/host_key_priv


- meta: flush_handlers

- service: name=httpd enabled=yes state=started
- service: name=cobblerd enabled=yes state=started       
- service: name=xinetd enabled=yes state=started


- name: Populate cobbler's loaders
  shell: cobbler get-loaders  
  args:
    creates: /var/lib/cobbler/loaders/pxelinux.0

  
- name: Check distro
  shell: cobbler distro list 
  register: distros
  changed_when: false
  
- name: Import missing distro (May take some time....)
  script: import.sh --url {{item.url}} --name {{item.name}}
  when: distros.stdout.find(item.name) == -1
  with_items: cobbler.distros
   
- name: Check repositories
  shell: cobbler repo list
  register: repositories
  changed_when: false
  
- name: Define missing repositories
  shell: cobbler repo add --name={{item.name}} --mirror={{item.mirror}} --keep-updated=Y --arch=x86_64 --mirror-locally=Y
  when: repositories.stdout.find(item.name) == -1
  with_items: cobbler.repositories

- name: Setup a cron for repository update
  cron: name="Reposync" job="cobbler reposync" minute="0" hour="3" state=present  
    
- name: Launch initial reposync (May take a long time)
  shell: cobler reposync
  args:
    create: /var/www/cobbler/repo_mirror/centos7epel 
  
  
  
  
  
  
  
  