---
# Copyright (C) 2015 BROADSoftware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
#limitations under the License.
#


# May be /sys/kernel/mm/redhat_transparent_hugepage/defrag or /sys/kernel/mm/transparent_hugepage/defrag
- name: Fetch the real name of transparent_hugepage control
  shell: "echo  /sys/kernel/mm/*ransparent_hugepage"
  register: thp_path
  changed_when: false
  
#- debug: var=thp_path.stdout

- name : Turn off Transparent Huge Page after reboot
  blockinfile :
    dest: /etc/rc.local
    backup: yes
    marker: "# {mark} Ansible managed block"
    content: |
             if test -f {{thp_path.stdout}}/enabled; then
               echo never > {{thp_path.stdout}}/enabled
             fi
             if test -f {{thp_path.stdout}}/defrag; then
               echo never > {{thp_path.stdout}}/defrag
             fi
  notify: Launch /etc/rc.local


- name : Tune OS block readahead to 8K (/etc/rc/local)
  blockinfile :
    dest: /etc/rc.local
    backup: yes
    marker: "# {mark}  ({{item.disk}}) Ansible managed block"
    content: echo 'blockdev --setra 8192 {{item.disk}}1'
  with_items: "{{disk_additional_disks}}"
  notify: Launch /etc/rc.local


- name: Tune swapiness
  sysctl: name=vm.swappiness value=0 state=present reload=yes


- name : Tune Soft file Limit 
  lineinfile: dest=/etc/security/limits.conf
              regexp="^\*\s+soft nofile.*"
              insertbefore="^# End of file"
              line="* soft nofile 65536"

- name : Tune Hard file Limit
  lineinfile: dest=/etc/security/limits.conf
              regexp="^\*\s+hard nofile.*"
              insertbefore="^# End of file"
              line="* hard nofile 65536"

- name : Tune Soft Process Limit
  lineinfile: dest=/etc/security/limits.conf
              regexp="^\*\s+soft nproc.*"
              insertbefore="^# End of file"
              line="* soft nproc 65536"

- name : Tune Hard Process Limit
  lineinfile: dest=/etc/security/limits.conf
              regexp="^\*\s+hard nproc.*"
              insertbefore="^# End of file"
              line="* hard nproc 65536"



