 
- name: Install some utilities
  yum: 
    name: htop,iotop,iftop,ntp,mlocate,sudo,net-tools,bind-utils
    state: present
    
- name: Launch some services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes        
  with_items:
    - ntpd
    

    
    