---
# Copyright (C) 2015 BROADSoftware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
#limitations under the License.
#


- name: Create yarn user
  user:
    name: yarn
    system: true
    createhome: no
    group: hadoop
    shell: /sbin/nologin
    home: /tmp
    state: present

- name: Create yarn log dir
  file: path=/var/log/yarn state=directory owner=yarn group=hadoop mode=0755

- name: Create yarn pid dir
  file: path=/var/run/yarn state=directory owner=yarn group=hadoop mode=0755
 
- name: Adjust yarn-config.sh
  blockinfile:
    dest: /opt/hadoop-{{ hadoop_version }}/libexec/yarn-config.sh
    backup: yes
    insertafter: "limitations under the License\\."
    marker: "# {mark} Ansible managed block"
    content: |
      export JAVA_HOME=/usr/java/default;
      export YARN_LOG_DIR=/var/log/yarn;
      export YARN_PID_DIR=/var/run/yarn;
  notify:
  - restart yarn-rm  
  - restart yarn-nm
 
- name: Setup yarn-site.xml
  template:
    src: "yarn-site.xml.j2"
    dest: "/opt/hadoop-{{ hadoop_version }}/etc/hadoop/yarn-site.xml"
    owner: yarn
    group: hadoop
    mode: 0644
    backup: yes
  notify:
  - restart yarn-rm  
  - restart yarn-nm
  
 
- name: Setup yarn command
  template:
    src: "yarn.j2"
    dest: "/usr/bin/yarn"
    owner: yarn
    group: hadoop
    mode: 0755
    backup: no
   
  
# --------------------------- Service creation  

- name: Create yarn-rm service
  template:
    src: "yarn-rm.service.j2"
    dest: "/usr/lib/systemd/system/yarn-rm.service"
    owner: root
    group: root
    mode: 0644
    backup: no
  when: ansible_nodename in groups['yarn_rm']
  notify:
  - reload service file
  - restart yarn-rm  
  - restart yarn-nm
        
   
- name: Create yarn-nm service
  template:
    src: yarn-nm.service.j2
    dest: /usr/lib/systemd/system/yarn-nm.service
    owner: root
    group: root
    mode: 0644
    backup: no
  when: ansible_nodename in groups['yarn_nm']
  notify:
  - reload service file
  - restart yarn-rm  
  - restart yarn-nm
  
   
        
# ----- service setup        

- meta: flush_handlers

- name: Ensure yarn-rm is started and enabled
  service:
    name: yarn-rm
    enabled: yes 
    state: started
  when: ansible_nodename in groups['yarn_rm']
      
   
- name: Ensure yarn-rm is started and enabled
  service:
    name: yarn-nm
    enabled: yes 
    state: started
  when: ansible_nodename in groups['yarn_nm']
        
   