---
# Copyright (C) 2015 BROADSoftware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
#limitations under the License.
#


# Required by some scripts

- yum: pkg=which state=present

- name: Create hadoop group
  group:
    name: hadoop
    system: true
    state: present

- name: Create hadoop user
  user:
    name: hadoop
    system: true
    createhome: no
    group: hadoop
    shell: /sbin/nologin
    home: /tmp
    state: present

    
- stat: path=/opt/hadoop-{{ hadoop_version }}
  register: hadoop_install    
- name: Download hadoop
  get_url: url="{{ hadoop_tgz_url }}" dest=/tmp
  when: not hadoop_install.stat.exists
- name: Unpack hadoop
  unarchive: copy=no creates=/opt/hadoop-{{ hadoop_version }} dest=/opt src=/tmp/hadoop-{{ hadoop_version }}.tar.gz owner=hadoop group=hadoop mode=0755
- name: Cleanup /tmp
  file: path=/tmp/hadoop-{{ hadoop_version }}.tar.gz state=absent
 

- name: Setup hadoop command
  template:
    src: "hadoop.j2"
    dest: "/usr/bin/hadoop"
    owner: hadoop
    group: hadoop
    mode: 0755
    backup: no
