---
# Copyright (C) 2016 BROADSoftware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
#limitations under the License.
#



# Use stat for reducing execution time in case of already installed.
- stat: path=/bin/jdctopic
  register: jdctopic

- name: Install jdctopic 
  yum:
    name: "{{ jdctopic_rpm_url }}"
    state: present
  when: not jdctopic.stat.exists

# Mainly to set zookeeper variable, if a group 'zookeepers' exists in inventory
- name: Configure jdctopic    
  template: src={{item}}.j2 dest=/etc/jdctopic/{{item}} owner=root group=root mode=0644
  with_items:
  - setenv.sh
  - log4j.xml

- name: Create a temporary file
  shell: mktemp
  register: mktemp
  changed_when: false

- name: Generate the description file
  template: src=description.yml.j2 dest={{mktemp.stdout}} mode=0644
  changed_when: false

- name: Apply potential update
  shell: jdctopic --inputFile {{mktemp.stdout}} --defaultState {{jdctopic_defaultState|default('present')}}
  register: jdct
  changed_when: jdct.stdout.find("0 modification(s)") == -1

- name: Cleanup temporary file
  file: path={{mktemp.stdout}} state=absent
  changed_when: false
  
  
  