---
- name: Restart cobblerd
  service: name=cobblerd state=restarted

- name: Restart httpd
  service: name=httpd state=restarted

# We need to be sure xinetd was restarted after a cobler sync
- name: Cobbler sync
  shell: cobbler sync; systemctl restart xinetd

- name: Restart xinetd
  service: name=xinetd state=restarted
